import {
	TransactionCategory,
	TransactionPaymentMethod,
	TransactionType,
	TransactionSubcategory,
} from "@prisma/client";

export const TRANSACTION_PAYMENT_METHOD_ICONS = {
	[TransactionPaymentMethod.CREDIT_CARD]: "credit-card.svg",
	[TransactionPaymentMethod.DEBIT_CARD]: "debit-card.svg",
	[TransactionPaymentMethod.BANK_TRANSFER]: "bank-transfer.svg",
	[TransactionPaymentMethod.BANK_SLIP]: "bank-slip.svg",
	[TransactionPaymentMethod.CASH]: "money.svg",
	[TransactionPaymentMethod.PIX]: "pix.svg",
	[TransactionPaymentMethod.OTHER]: "other.svg",
} as const;

export const TRANSACTION_CATEGORY_LABELS: Record<TransactionCategory, string> =
	{
		[TransactionCategory.SALARY]: "Salário",
		[TransactionCategory.EDUCATION]: "Educação",
		[TransactionCategory.FOOD]: "Alimentação",
		[TransactionCategory.HEALTH]: "Saúde",
		[TransactionCategory.HOUSING]: "Habitação",
		[TransactionCategory.TRANSPORTATION]: "Transporte",
		[TransactionCategory.BUSINESS_EXPENSES]: "Despesas de Negócios",
		[TransactionCategory.PUBLIC_UTILITIES]: "Contas Serviços Públicos",
		[TransactionCategory.TAXES]: "Impostos",
		[TransactionCategory.CREDIT_CARD_BILL]: "Fatura de Cartão",
		[TransactionCategory.BANK_BILLS]: "Boletos Bancários",
		[TransactionCategory.SUBSCRIPTIONS]: "Assinaturas",
		[TransactionCategory.INSURANCE]: "Seguros",
		[TransactionCategory.ENTERTAINMENT]: "Entretenimento",
		[TransactionCategory.TRAVEL]: "Viagens",
		[TransactionCategory.UTILITY]: "Utilidades",
		[TransactionCategory.SHOPPING]: "Compras",
		[TransactionCategory.INVESTMENTS]: "Aplicações",
		[TransactionCategory.OTHER]: "Outros",
	} as const;

export const TRANSACTION_PAYMENT_METHOD_LABELS: Record<
	TransactionPaymentMethod,
	string
> = {
	[TransactionPaymentMethod.CREDIT_CARD]: "Cartão de Crédito",
	[TransactionPaymentMethod.DEBIT_CARD]: "Cartão de Débito",
	[TransactionPaymentMethod.BANK_TRANSFER]: "Transferência Bancária",
	[TransactionPaymentMethod.BANK_SLIP]: "Boleto Bancário",
	[TransactionPaymentMethod.CASH]: "Dinheiro",
	[TransactionPaymentMethod.PIX]: "Pix",
	[TransactionPaymentMethod.OTHER]: "Outros",
} as const;

export const TRANSACTION_TYPE_OPTIONS = [
	{
		value: TransactionType.DEPOSIT,
		label: "Depósitos",
	},
	{
		value: TransactionType.EXPENSE,
		label: "Despesas",
	},
	{
		value: TransactionType.INVESTMENT,
		label: "Investimentos",
	},
] as const;

export const TRANSACTION_PAYMENT_METHOD_OPTIONS = [
	{
		value: TransactionPaymentMethod.CREDIT_CARD,
		label:
			TRANSACTION_PAYMENT_METHOD_LABELS[TransactionPaymentMethod.CREDIT_CARD],
	},
	{
		value: TransactionPaymentMethod.DEBIT_CARD,
		label: TRANSACTION_PAYMENT_METHOD_LABELS[TransactionPaymentMethod.DEBIT_CARD],
	},
	{
		value: TransactionPaymentMethod.BANK_TRANSFER,
		label:
			TRANSACTION_PAYMENT_METHOD_LABELS[TransactionPaymentMethod.BANK_TRANSFER],
	},
	{
		value: TransactionPaymentMethod.BANK_SLIP,
		label: TRANSACTION_PAYMENT_METHOD_LABELS[TransactionPaymentMethod.BANK_SLIP],
	},
	{
		value: TransactionPaymentMethod.CASH,
		label: TRANSACTION_PAYMENT_METHOD_LABELS[TransactionPaymentMethod.CASH],
	},
	{
		value: TransactionPaymentMethod.PIX,
		label: TRANSACTION_PAYMENT_METHOD_LABELS[TransactionPaymentMethod.PIX],
	},
	{
		value: TransactionPaymentMethod.OTHER,
		label: TRANSACTION_PAYMENT_METHOD_LABELS[TransactionPaymentMethod.OTHER],
	},
] as const;

export const TRANSACTION_CATEGORY_OPTIONS = [
	{
		value: TransactionCategory.SALARY,
		label: TRANSACTION_CATEGORY_LABELS[TransactionCategory.SALARY],
	},
	{
		value: TransactionCategory.EDUCATION,
		label: TRANSACTION_CATEGORY_LABELS[TransactionCategory.EDUCATION],
	},
	{
		value: TransactionCategory.FOOD,
		label: TRANSACTION_CATEGORY_LABELS[TransactionCategory.FOOD],
	},
	{
		value: TransactionCategory.HEALTH,
		label: TRANSACTION_CATEGORY_LABELS[TransactionCategory.HEALTH],
	},
	{
		value: TransactionCategory.HOUSING,
		label: TRANSACTION_CATEGORY_LABELS[TransactionCategory.HOUSING],
	},
	{
		value: TransactionCategory.TRANSPORTATION,
		label: TRANSACTION_CATEGORY_LABELS[TransactionCategory.TRANSPORTATION],
	},
	{
		value: TransactionCategory.BUSINESS_EXPENSES,
		label: TRANSACTION_CATEGORY_LABELS[TransactionCategory.BUSINESS_EXPENSES],
	},
	{
		value: TransactionCategory.PUBLIC_UTILITIES,
		label: TRANSACTION_CATEGORY_LABELS[TransactionCategory.PUBLIC_UTILITIES],
	},
	{
		value: TransactionCategory.TAXES,
		label: TRANSACTION_CATEGORY_LABELS[TransactionCategory.TAXES],
	},
	{
		value: TransactionCategory.CREDIT_CARD_BILL,
		label: TRANSACTION_CATEGORY_LABELS[TransactionCategory.CREDIT_CARD_BILL],
	},
	{
		value: TransactionCategory.BANK_BILLS,
		label: TRANSACTION_CATEGORY_LABELS[TransactionCategory.BANK_BILLS],
	},
	{
		value: TransactionCategory.SUBSCRIPTIONS,
		label: TRANSACTION_CATEGORY_LABELS[TransactionCategory.SUBSCRIPTIONS],
	},
	{
		value: TransactionCategory.INSURANCE,
		label: TRANSACTION_CATEGORY_LABELS[TransactionCategory.INSURANCE],
	},
	{
		value: TransactionCategory.ENTERTAINMENT,
		label: TRANSACTION_CATEGORY_LABELS[TransactionCategory.ENTERTAINMENT],
	},
	{
		value: TransactionCategory.TRAVEL,
		label: TRANSACTION_CATEGORY_LABELS[TransactionCategory.TRAVEL],
	},
	{
		value: TransactionCategory.UTILITY,
		label: TRANSACTION_CATEGORY_LABELS[TransactionCategory.UTILITY],
	},
	{
		value: TransactionCategory.SHOPPING,
		label: TRANSACTION_CATEGORY_LABELS[TransactionCategory.SHOPPING],
	},
	{
		value: TransactionCategory.INVESTMENTS,
		label: TRANSACTION_CATEGORY_LABELS[TransactionCategory.INVESTMENTS],
	},
	{
		value: TransactionCategory.OTHER,
		label: TRANSACTION_CATEGORY_LABELS[TransactionCategory.OTHER],
	},
] as const;

export const TRANSACTION_SUBCATEGORY_LABELS: Record<
	TransactionSubcategory,
	string
> = {
	[TransactionSubcategory.MONTHLY_SALARY]: "Salário Mensal",
	[TransactionSubcategory.SALARY_ADVANCE]: "Adiantamento de Salário",
	[TransactionSubcategory.COMMISSIONS]: "Comissões",
	[TransactionSubcategory.BENEFITS]: "Benefícios",
	[TransactionSubcategory.PROFIT_SHARING]: "Participação nos Lucros",
	[TransactionSubcategory.VARIABLE_COMPENSATION]: "Remuneração Variável",
	[TransactionSubcategory.INDIRECT_SALARY]: "Salário Indireto (Extras)",
	[TransactionSubcategory.PRO_LABORE]: "Pró-Labore",
	[TransactionSubcategory.BONUSES]: "Bônus",
	[TransactionSubcategory.REGISTRATION]: "Matrícula",
	[TransactionSubcategory.MONTHLY_PAYMENT]: "Mensalidade",
	[TransactionSubcategory.SCHOOL_SUPPLIES]: "Material",
	[TransactionSubcategory.UNIFORM]: "Uniformes",
	[TransactionSubcategory.SCHOOL_TRANSPORT]: "Transporte Escolar",
	[TransactionSubcategory.SCHOOL_MEALS]: "Refeições Escolares",
	[TransactionSubcategory.EXTRACURRICULAR_ACTIVITIES]:
		"Atividades Extracurriculares",
	[TransactionSubcategory.MEALS_OUT]: "Refeições Fora",
	[TransactionSubcategory.FAST_FOOD_DELIVERY]: "Fast Food / Delivery",
	[TransactionSubcategory.SUPERMARKET]: "Supermercado",
	[TransactionSubcategory.BUTCHER_SHOP]: "Açougue",
	[TransactionSubcategory.BAKERY]: "Padaria",
	[TransactionSubcategory.FARMERS_MARKET]: "Feira Livre / Sacolão",
	[TransactionSubcategory.HEALTH_PLANS]: "Planos de Saúde",
	[TransactionSubcategory.MEDICAL_CONSULTATIONS_EXAMS]:
		"Consultas Médicas / Exames",
	[TransactionSubcategory.PHARMACY]: "Farmácia",
	[TransactionSubcategory.HOSPITALIZATIONS]: "Internações",
	[TransactionSubcategory.DENTIST]: "Dentista",
	[TransactionSubcategory.THERAPY]: "Terapia",
	[TransactionSubcategory.HOME_LOAN]: "Empréstimo Habitacional",
	[TransactionSubcategory.RENT]: "Aluguel",
	[TransactionSubcategory.CONDOMINIUM]: "Condomínio",
	[TransactionSubcategory.LPG]: "Gás de Cozinha",
	[TransactionSubcategory.MAINTENANCE_REFORMS]: "Manutenção / Reformas",
	[TransactionSubcategory.FURNITURE_APPLIANCES]: "Móveis / Eletrodomésticos",
	[TransactionSubcategory.FUEL]: "Combustível",
	[TransactionSubcategory.MAINTENANCE]: "Manutenção",
	[TransactionSubcategory.LICENSING]: "Licenciamento",
	[TransactionSubcategory.PARKING]: "Estacionamento",
	[TransactionSubcategory.FINES]: "Multas",
	[TransactionSubcategory.TOLLS]: "Pedágios",
	[TransactionSubcategory.TICKETS]: "Passagens",
	[TransactionSubcategory.TRANSPORT_VOUCHERS]: "Vale-Transporte",
	[TransactionSubcategory.UBER_TAXIS]: "Uber / Táxis",
	[TransactionSubcategory.FIXED_EXPENSES]: "Despesas Fixas",
	[TransactionSubcategory.VARIABLE_EXPENSES]: "Despesas Variáveis",
	[TransactionSubcategory.DIRECT_COSTS]: "Custos Diretos",
	[TransactionSubcategory.INDIRECT_COSTS]: "Custos Indiretos",
	[TransactionSubcategory.ELECTRICITY]: "Energia Elétrica",
	[TransactionSubcategory.WATER]: "Água",
	[TransactionSubcategory.TELEPHONY]: "Telefonia",
	[TransactionSubcategory.BASIC_SANITATION]: "Saneamento Básico",
	[TransactionSubcategory.MOTOR_VEHICLE_TAX]: "IPVA",
	[TransactionSubcategory.PROPERTY_TAX]: "IPTU",
	[TransactionSubcategory.INDIVIDUAL_INCOME_TAX]: "IRPF",
	[TransactionSubcategory.SALES_TAX]: "ISS",
	[TransactionSubcategory.RURAL_PROPERTY_TAX]: "ITR",
	[TransactionSubcategory.INHERITANCE_TAX]: "ITCMD",
	[TransactionSubcategory.INTEGRAL]: "Integral",
	[TransactionSubcategory.MINIMUM_PAYMENT]: "Pagtº Mínimo",
	[TransactionSubcategory.PAYMENT_IN_INSTALLMENTS]: "Pagtº Parcelado",
	[TransactionSubcategory.ANTICIPATION]: "Antecipação",
	[TransactionSubcategory.INTEREST_CHARGES]: "Juros / Encargos",
	[TransactionSubcategory.AUTOMATIC_DEBIT]: "Débito Automático",
	[TransactionSubcategory.FULL_ON_TIME]: "Integral no vencimento",
	[TransactionSubcategory.FULL_OVERDUE]: "Integral em Atraso",
	[TransactionSubcategory.INTERNET]: "Internet",
	[TransactionSubcategory.MOBILE_PHONE]: "Celular",
	[TransactionSubcategory.MOBILE_DATA]: "Dados Móveis",
	[TransactionSubcategory.VIDEO_STREAMING]: "Streaming de Vídeos",
	[TransactionSubcategory.MUSIC_STREAMING]: "Streaming de Músicas",
	[TransactionSubcategory.PAY_TV]: "TV por Assinatura",
	[TransactionSubcategory.SOFTWARES]: "Softwares",
	[TransactionSubcategory.GYM]: "Academia",
	[TransactionSubcategory.LIFE_INSURANCE]: "Seguro de Vida",
	[TransactionSubcategory.HOME_INSURANCE]: "Seguro Residencial",
	[TransactionSubcategory.AUTO_INSURANCE]: "Seguro Veículos",
	[TransactionSubcategory.HEALTH_INSURANCE]: "Seguro Saúde",
	[TransactionSubcategory.TRAVEL_INSURANCE]: "Seguro Viagem",
	[TransactionSubcategory.FUNERAL_INSURANCE]: "Seguro Funeral",
	[TransactionSubcategory.PRIVATE_RETIREMENT_PLAN]: "Previdência Privada",
	[TransactionSubcategory.MOVIE_THEATER]: "Cinema",
	[TransactionSubcategory.THEATER]: "Teatro",
	[TransactionSubcategory.SHOWS_EVENTS]: "Shows / Eventos",
	[TransactionSubcategory.MISCELLANEOUS_OUTINGS]: "Passeios Diversos",
	[TransactionSubcategory.LOUNGE_BAR]: "Lazer Noturno / Pubs",
	[TransactionSubcategory.NIGHTCLUB]: "Nightclub / Balada",
	[TransactionSubcategory.PARTY]: "Festa",
	[TransactionSubcategory.HOBBIES]: "Hobbies",
	[TransactionSubcategory.HOSTING]: "Hospedagem",
	[TransactionSubcategory.TRANSPORT]: "Transporte",
	[TransactionSubcategory.GASTRONOMY]: "Gastronomia",
	[TransactionSubcategory.LEISURE_ACTIVITIES]: "Atividades de Lazer",
	[TransactionSubcategory.SMALL_HOUSEHOLD_ITEMS]: "Utilidades Domésticas",
	[TransactionSubcategory.MAINTENANCE_SUPPLIES]: "Suprimentos de Manutenção",
	[TransactionSubcategory.CLEANING_PRODUCTS]: "Produtos de Limpeza",
	[TransactionSubcategory.OTHER]: "Outros (especificar)",
	[TransactionSubcategory.ONLINE_SHOPPING]: "Compras Online",
	[TransactionSubcategory.CLOTHING_ACCESSORIES]: "Roupas / Acessórios",
	[TransactionSubcategory.SHOES_FOOTWEAR]: "Calçados",
	[TransactionSubcategory.ELECTRONICS]: "Eletrônicos",
	[TransactionSubcategory.HOME_DECOR]: "Decoração",
	[TransactionSubcategory.BOOKS_STATIONERY]: "Livros e Papelaria",
	[TransactionSubcategory.GIFTS]: "Presentes",
	[TransactionSubcategory.DEPARTMENT_STORES]: "Lojas de Departamento",
	[TransactionSubcategory.BEAUTY_PRODUCTS]: "Produtos de Beleza",
	[TransactionSubcategory.SAVINGS_ACCOUNT]: "Poupança",
	[TransactionSubcategory.STOCKS]: "Ações",
	[TransactionSubcategory.BANK_CERTIFICATES_OF_DEPOSIT]: "CDBs e RDBs",
	[TransactionSubcategory.REAL_ESTATE_CREDIT_BONDS]: "LCIs e LCAs",
	[TransactionSubcategory.INVESTMENT_FUNDS]: "Fundos de Investimento",
	[TransactionSubcategory.REAL_ESTATE_INVESTMENTS]: "Imóveis",
	[TransactionSubcategory.REITS]: "Fundos Imobiliários",
	[TransactionSubcategory.GOVERNMENT_BONDS]: "Tesouro Direto",
	[TransactionSubcategory.CRYPTOCURRENCIES]: "Criptomoedas",
	[TransactionSubcategory.SPECIFY]: "Especificar",
} as const;

export const TRANSACTION_SUBCATEGORY_MAP: Record<
	TransactionCategory,
	TransactionSubcategory[]
> = {
	[TransactionCategory.SALARY]: [
		TransactionSubcategory.MONTHLY_SALARY,
		TransactionSubcategory.SALARY_ADVANCE,
		TransactionSubcategory.COMMISSIONS,
		TransactionSubcategory.BENEFITS,
		TransactionSubcategory.PROFIT_SHARING,
		TransactionSubcategory.VARIABLE_COMPENSATION,
		TransactionSubcategory.INDIRECT_SALARY,
		TransactionSubcategory.PRO_LABORE,
		TransactionSubcategory.BONUSES,
	],
	[TransactionCategory.EDUCATION]: [
		TransactionSubcategory.REGISTRATION,
		TransactionSubcategory.MONTHLY_PAYMENT,
		TransactionSubcategory.SCHOOL_SUPPLIES,
		TransactionSubcategory.UNIFORM,
		TransactionSubcategory.SCHOOL_TRANSPORT,
		TransactionSubcategory.SCHOOL_MEALS,
		TransactionSubcategory.EXTRACURRICULAR_ACTIVITIES,
	],
	[TransactionCategory.FOOD]: [
		TransactionSubcategory.MEALS_OUT,
		TransactionSubcategory.FAST_FOOD_DELIVERY,
		TransactionSubcategory.SUPERMARKET,
		TransactionSubcategory.BUTCHER_SHOP,
		TransactionSubcategory.BAKERY,
		TransactionSubcategory.FARMERS_MARKET,
	],
	[TransactionCategory.HEALTH]: [
		TransactionSubcategory.HEALTH_PLANS,
		TransactionSubcategory.MEDICAL_CONSULTATIONS_EXAMS,
		TransactionSubcategory.PHARMACY,
		TransactionSubcategory.HOSPITALIZATIONS,
		TransactionSubcategory.DENTIST,
		TransactionSubcategory.THERAPY,
	],
	[TransactionCategory.HOUSING]: [
		TransactionSubcategory.HOME_LOAN,
		TransactionSubcategory.RENT,
		TransactionSubcategory.CONDOMINIUM,
		TransactionSubcategory.LPG,
		TransactionSubcategory.MAINTENANCE_REFORMS,
		TransactionSubcategory.FURNITURE_APPLIANCES,
	],
	[TransactionCategory.TRANSPORTATION]: [
		TransactionSubcategory.FUEL,
		TransactionSubcategory.MAINTENANCE,
		TransactionSubcategory.LICENSING,
		TransactionSubcategory.PARKING,
		TransactionSubcategory.FINES,
		TransactionSubcategory.TOLLS,
		TransactionSubcategory.TICKETS,
		TransactionSubcategory.TRANSPORT_VOUCHERS,
		TransactionSubcategory.UBER_TAXIS,
	],
	[TransactionCategory.BUSINESS_EXPENSES]: [
		TransactionSubcategory.DIRECT_COSTS,
		TransactionSubcategory.INDIRECT_COSTS,
		TransactionSubcategory.FIXED_EXPENSES,
		TransactionSubcategory.VARIABLE_EXPENSES,
	],
	[TransactionCategory.PUBLIC_UTILITIES]: [
		TransactionSubcategory.ELECTRICITY,
		TransactionSubcategory.WATER,
		TransactionSubcategory.TELEPHONY,
		TransactionSubcategory.BASIC_SANITATION,
	],
	[TransactionCategory.TAXES]: [
		TransactionSubcategory.MOTOR_VEHICLE_TAX,
		TransactionSubcategory.PROPERTY_TAX,
		TransactionSubcategory.INDIVIDUAL_INCOME_TAX,
		TransactionSubcategory.SALES_TAX,
		TransactionSubcategory.RURAL_PROPERTY_TAX,
		TransactionSubcategory.INHERITANCE_TAX,
	],
	[TransactionCategory.CREDIT_CARD_BILL]: [
		TransactionSubcategory.INTEGRAL,
		TransactionSubcategory.MINIMUM_PAYMENT,
		TransactionSubcategory.PAYMENT_IN_INSTALLMENTS,
		TransactionSubcategory.ANTICIPATION,
		TransactionSubcategory.INTEREST_CHARGES,
		TransactionSubcategory.AUTOMATIC_DEBIT,
	],
	[TransactionCategory.BANK_BILLS]: [
		TransactionSubcategory.FULL_ON_TIME,
		TransactionSubcategory.FULL_OVERDUE,
		TransactionSubcategory.ANTICIPATION,
		TransactionSubcategory.AUTOMATIC_DEBIT,
	],
	[TransactionCategory.SUBSCRIPTIONS]: [
		TransactionSubcategory.INTERNET,
		TransactionSubcategory.MOBILE_PHONE,
		TransactionSubcategory.MOBILE_DATA,
		TransactionSubcategory.VIDEO_STREAMING,
		TransactionSubcategory.MUSIC_STREAMING,
		TransactionSubcategory.PAY_TV,
		TransactionSubcategory.SOFTWARES,
		TransactionSubcategory.GYM,
	],
	[TransactionCategory.INSURANCE]: [
		TransactionSubcategory.LIFE_INSURANCE,
		TransactionSubcategory.HOME_INSURANCE,
		TransactionSubcategory.AUTO_INSURANCE,
		TransactionSubcategory.HEALTH_INSURANCE,
		TransactionSubcategory.TRAVEL_INSURANCE,
		TransactionSubcategory.FUNERAL_INSURANCE,
		TransactionSubcategory.PRIVATE_RETIREMENT_PLAN,
	],
	[TransactionCategory.ENTERTAINMENT]: [
		TransactionSubcategory.MOVIE_THEATER,
		TransactionSubcategory.THEATER,
		TransactionSubcategory.SHOWS_EVENTS,
		TransactionSubcategory.MISCELLANEOUS_OUTINGS,
		TransactionSubcategory.LOUNGE_BAR,
		TransactionSubcategory.NIGHTCLUB,
		TransactionSubcategory.PARTY,
		TransactionSubcategory.HOBBIES,
	],
	[TransactionCategory.TRAVEL]: [
		TransactionSubcategory.HOSTING,
		TransactionSubcategory.TRANSPORT,
		TransactionSubcategory.GASTRONOMY,
		TransactionSubcategory.LEISURE_ACTIVITIES,
	],
	[TransactionCategory.UTILITY]: [
		TransactionSubcategory.SMALL_HOUSEHOLD_ITEMS,
		TransactionSubcategory.MAINTENANCE_SUPPLIES,
		TransactionSubcategory.CLEANING_PRODUCTS,
		TransactionSubcategory.OTHER,
	],
	[TransactionCategory.SHOPPING]: [
		TransactionSubcategory.ONLINE_SHOPPING,
		TransactionSubcategory.CLOTHING_ACCESSORIES,
		TransactionSubcategory.SHOES_FOOTWEAR,
		TransactionSubcategory.ELECTRONICS,
		TransactionSubcategory.HOME_DECOR,
		TransactionSubcategory.BOOKS_STATIONERY,
		TransactionSubcategory.GIFTS,
		TransactionSubcategory.DEPARTMENT_STORES,
		TransactionSubcategory.BEAUTY_PRODUCTS,
	],
	[TransactionCategory.INVESTMENTS]: [
		TransactionSubcategory.SAVINGS_ACCOUNT,
		TransactionSubcategory.STOCKS,
		TransactionSubcategory.BANK_CERTIFICATES_OF_DEPOSIT,
		TransactionSubcategory.REAL_ESTATE_CREDIT_BONDS,
		TransactionSubcategory.INVESTMENT_FUNDS,
		TransactionSubcategory.REAL_ESTATE_INVESTMENTS,
		TransactionSubcategory.REITS,
		TransactionSubcategory.GOVERNMENT_BONDS,
		TransactionSubcategory.CRYPTOCURRENCIES,
	],
	[TransactionCategory.OTHER]: [TransactionSubcategory.SPECIFY],
} as const;
