-- CreateEnum
CREATE TYPE "TransactionSubcategory" AS ENUM ('MONTHLY_SALARY', 'SALARY_ADVANCE', 'COMMISSIONS', 'BENEFITS', 'PROFIT_SHARING', 'VARIABLE_COMPENSATION', 'INDIRECT_SALARY', 'PRO_LABORE', 'REGISTRATION', 'MONTHLY_PAYMENT', 'SCHOOL_SUPPLIES', 'UNIFORM', 'SCHOOL_TRANSPORT', 'SCHOOL_MEALS', 'EXTRACURRICULAR_ACTIVITIES', 'MEALS_OUT', 'FAST_FOOD_DELIVERY', 'SUPERMARKET', 'BUTCHER_SHOP', 'BAKERY', 'FARMERS_MARKET', 'HEALTH_PLANS', 'MEDICAL_CONSULTATIONS_EXAMS', 'PHARMACY', 'HOSPITALIZATIONS', 'DENTIST', 'HOME_LOAN', 'RENT', 'CONDOMINIUM', 'LPG', 'MAINTENANCE_REFORMS', 'FURNITURE_APPLIANCES', 'FUEL', 'MAINTENANCE', 'LICENSING', 'PARKING', 'FINES', 'TICKETS', 'TRANSPORT_VOUCHERS', 'UBER_TAXIS', 'FIXED_EXPENSES', 'VARIABLE_EXPENSES', 'DIRECT_COSTS', 'INDIRECT_COSTS', 'ELECTRICITY', 'WATER', 'TELEPHONY', 'BASIC_SANITATION', 'MOTOR_VEHICLE_TAX', 'PROPERTY_TAX', 'INDIVIDUAL_INCOME_TAX', 'SALES_TAX', 'RURAL_PROPERTY_TAX', 'INHERITANCE_TAX', 'INTEGRAL', 'MINIMUM_PAYMENT', 'PAYMENT_IN_INSTALLMENTS', 'ANTICIPATION', 'INTEREST_CHARGES', 'AUTOMATIC_DEBIT', 'FULL_ON_TIME', 'FULL_OVERDUE', 'INTERNET', 'MOBILE_PHONE', 'MOBILE_DATA', 'VIDEO_STREAMING', 'MUSIC_STREAMING', 'PAY_TV', 'SOFTWARES', 'LIFE_INSURANCE', 'HOME_INSURANCE', 'AUTO_INSURANCE', 'HEALTH_INSURANCE', 'TRAVEL_INSURANCE', 'FUNERAL_INSURANCE', 'PRIVATE_RETIREMENT_PLAN', 'MOVIE_THEATER', 'THEATER', 'SHOWS_EVENTS', 'MISCELLANEOUS_OUTINGS', 'LOUNGE_BAR', 'NIGHTCLUB', 'PARTY', 'HOSTING', 'TRANSPORT', 'GASTRONOMY', 'LEISURE_ACTIVITIES', 'SMALL_HOUSEHOLD_ITEMS', 'MAINTENANCE_SUPPLIES', 'CLEANING_PRODUCTS', 'OTHER', 'ONLINE_SHOPPING', 'CLOTHING_ACCESSORIES', 'SHOES_FOOTWEAR', 'ELECTRONICS', 'HOME_DECOR', 'BOOKS_STATIONERY', 'GIFTS', 'DEPARTMENT_STORES', 'BEAUTY_PRODUCTS', 'SAVINGS_ACCOUNT', 'STOCKS', 'BANK_CERTIFICATES_OF_DEPOSIT', 'REAL_ESTATE_CREDIT_BONDS', 'INVESTMENT_FUNDS', 'REAL_ESTATE_INVESTMENTS', 'REITS', 'GOVERNMENT_BONDS', 'CRYPTOCURRENCIES', 'SPECIFY');

-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "TransactionCategory" ADD VALUE 'BUSINESS_EXPENSES';
ALTER TYPE "TransactionCategory" ADD VALUE 'PUBLIC_UTILITIES';
ALTER TYPE "TransactionCategory" ADD VALUE 'TAXES';
ALTER TYPE "TransactionCategory" ADD VALUE 'CREDIT_CARD_BILL';
ALTER TYPE "TransactionCategory" ADD VALUE 'BANK_BILLS';
ALTER TYPE "TransactionCategory" ADD VALUE 'SUBSCRIPTIONS';
ALTER TYPE "TransactionCategory" ADD VALUE 'INSURANCE';
ALTER TYPE "TransactionCategory" ADD VALUE 'TRAVEL';
ALTER TYPE "TransactionCategory" ADD VALUE 'SHOPPING';
ALTER TYPE "TransactionCategory" ADD VALUE 'INVESTMENTS';

-- AlterTable
ALTER TABLE "Transaction" ADD COLUMN     "subcategory" "TransactionSubcategory";
